# Generated by Django 6.0.2 on 2026-02-26 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moodentry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='reflection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='start_time',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.FloatField(help_text='Тривалість у годинах'),
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood', models.PositiveSmallIntegerField(choices=[(1, '😞 Very Low'), (2, '😕 Low'), (3, '😐 Neutral'), (4, '🙂 Good'), (5, '😄 Great')])),
                ('mental_energy', models.PositiveSmallIntegerField()),
                ('physical_energy', models.PositiveSmallIntegerField()),
                ('sleep_hours', models.FloatField(default=7.0)),
                ('hydration', models.FloatField(default=6.0)),
                ('screen_time', models.FloatField(default=4.0)),
                ('movement_min', models.FloatField(default=30.0)),
                ('reflection', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='HealthLog',
        ),
        migrations.DeleteModel(
            name='MoodEntry',
        ),
        migrations.DeleteModel(
            name='Reflection',
        ),
    ]
